version: '3.8'

services:
  grpc-server:
    build: ./grpc-server
    ports:
      - "50051:50051"

  graphql-bff:
    build: ./graphql-bff
    ports:
      - "4000:4000"
    depends_on:
      - grpc-server
